export const GRADES = [
  'Grade 1',
  'Grade 2',
  'Grade 3',
  'Grade 4',
  'Grade 5',
  'Grade 6',
  'Grade 7',
  'Grade 8',
  'Grade 9',
  'Grade 10',
  'Grade 11',
  'Grade 12'
];

export const SUBJECTS = [
  'Quran',
  'Islamic Education',
  'Arabic',
  'English',
  'Mathematics',
  'Science',
  'Physics',
  'Chemistry',
  'Biology',
  'History',
  'Geography',
  'Philosophy',
  'Social Studies',
  'General Science',
  'Computer Science',
  'Art',
  'Music',
  'القرآن الكريم',
  'التربية الإسلامية',
  'اللغة العربية',
  'الرياضيات',
  'الدراسات الاجتماعية',
  'العلوم العامة',
  'الكيمياء',
  'الفيزياء',
  'الأحياء',
  'التاريخ',
  'الجغرافيا',
  'الفلسفة',
  'الإنجليزية'
];
